//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudOperationsWithReactJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSold
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long ProductId { get; set; }
        public long StoreId { get; set; }
        public System.DateTime DateSold { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer1 Customer1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
